#select the mode to test, which can be property, assertion, overflow, exploration, optimization
testMode: "assertion"
#format can be "text" or "json" for different output (human or machine readable)
format: "text"
#checkAsserts checks assertions
checkAsserts: true
#coverage controls coverage guided testing
coverage: false
#maximum time between generated txs; default is one week
maxTimeDelay: 31556952 # approximately 1 year
#solcArgs allows special args to solc
solcArgs: "--optimize --optimize-runs 200 --via-ir"
#solcLibs is solc libraries
#solcLibs: ["node_modules/@openzeppelin"]