#select the mode to test, which can be property, assertion, overflow, exploration, optimization
testMode: assertion
#maximum time between generated txs; default is one week
maxTimeDelay: 31556952 # approximately 1 year
#solcArgs allows special args to solc
solcArgs: "--optimize --optimize-runs 200"
#testLimit is the number of test sequences to run
testLimit: 10000
#seqLen defines how many transactions are in a test sequence
seqLen: 100
corpus-dir: corpus