name: "Deploy"
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:
    inputs:
      endpoint:
        description: 'endpoint used to deploy contracts'
        default: https://acala-mandala.api.onfinality.io/public
        required: true
      network:
        type: choice
        description: 'network used to publish contracts'
        default: testnet
        required: true
        options: 
        - testnet
        - moonbase

jobs:
  Deploy-Contracts:
    name: Deploy-Contracts
    if: "startsWith(github.event.head_commit.message, '[deploy-testnet]') && github.repository == 'subquery/network-contracts' || github.event_name == 'workflow_dispatch'"
    runs-on: ubuntu-latest
    env:
      SEED: ${{ secrets.SEED }}
    steps:
      #Check out
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'

      - run: yarn

      - name: Bump & Build
        run: npm version prerelease --no-git-tag-version && yarn build

      # Deploy contracts to acala testnet
      - name: Deploy contracts
        run: yarn deploy:${{ github.event.inputs.network }} && scripts/copy_deployment_json.sh # Uses SEED env var
        env:
          ENDPOINT: ${{ github.event.inputs.endpoint }}
          DEPLOY_PRINT: true

      - uses: JS-DevTools/npm-publish@v1
        name: Publish
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: dev
          access: public
          package: build/build/package.json

      # Commit updated contract addresses, this should trigger the prerelease action
      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        with:
          add: publish/testnet.json package.json
          message: '[SKIP CI] Deploy to testnet and Prerelease'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Seed data
        run: yarn seed:testnet
