name: Deploy Doucments
on:
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Yarn
              run: yarn

            - name: Generate Contract Documents
              run: yarn docs:generate

            - name: Deploy documents to Github Page
              uses: jenkey2011/vuepress-deploy@master
              env:
                  ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BUILD_SCRIPT: yarn docs:build
                  BUILD_DIR: docs/.vuepress/dist/
