name: Fuzz

on:
  push:
    branches:
      - kepler/fuzz
  pull_request:

jobs:
  echidna:
    name: Echidna
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testName:
          - PermissionedExchangeEchidnaTest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
      
      - run: yarn

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install crytic-compile
        run: pip3 install crytic-compile

      - name: Install solc-select
        run: pip3 install solc-select

      - name: Solc Select 0.8.15
        run: |
          solc-select install 0.8.15
          solc-select use 0.8.15
      - name: Crytic Compile ${{ matrix.testName }}
        run: |
          crytic-compile test-fuzz/${{ matrix.testName }}.sol --solc-args "--optimize --optimize-runs 200 --via-ir" --export-format solc
          jq --sort-keys . crytic-export/combined_solc.json > sorted_crytic_solc.json
      
      - name: Cache ${{ matrix.testName }} Corpus
        uses: actions/cache@v2
        with:
          path: corpus
          key: abi-${{ matrix.testName }}-${{ hashFiles('**/sorted_crytic_solc.json') }}-v3

      - name: Fuzz ${{ matrix.testName }}
        uses: crytic/echidna-action@v2
        with:
          files: test-fuzz/${{ matrix.testName }}.sol
          contract: ${{ matrix.testName }}
          config: echidna.config.ci.yml
          corpus-dir: corpus
          test-mode: assertion
          test-limit: 250000
          seq-len: 100
          solc-version: 0.8.15
          echidna-version: v2.0.0

      