name: Fuzz

on:
  push:
    branches:
      - kepler/fuzz
  pull_request:

jobs:
  echidna:
    name: Echidna
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testName:
          - PermissionedExchangeEchidnaTest

    steps:
      - uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pip3
        run: |
          python -m pip install --upgrade pip
      - name: Install slither
        run: |
          pip3 install slither-analyzer
      - name: Install solc-select
        run: |
          pip3 install solc-select
      - name: Set solc v0.8.15
        run: |
          solc-select install 0.8.15
          solc-select use 0.8.15
      - name: Install echidna
        run: |
          sudo wget -O /tmp/echidna-test.tar.gz https://github.com/crytic/echidna/releases/download/v1.7.1/echidna-test-1.7.1-Ubuntu-18.04.tar.gz
          sudo tar -xf /tmp/echidna-test.tar.gz -C /usr/bin
          sudo chmod +x /usr/bin/echidna-test
      - name: Run ${{ matrix.testName }}
        run: echidna-test test-fuzz/PermissionedExchangeEchidnaTest.sol --contract ${{ matrix.testName }} --config echidna.config.ci.yml --check-asserts