name: PR
on:
  pull_request:
    paths-ignore:

jobs:
  pr:
    name: pr
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: yarn
    - name: build
      run: yarn build
    - name: lint
      run: yarn lint
    - name: test
      run: yarn test
