name: "Upgrade"
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:
    inputs:
      endpoint:
        description: 'endpoint used to deploy contracts'
        default: https://polygon-mumbai.infura.io/v3/4458cf4d1689497b9a38b1d6bbf05e78
        required: true
      network:
        type: choice
        description: 'network used to publish contracts'
        default: testnet
        required: true
        options:
          - testnet

jobs:
  Upgrade-Contracts:
    name: Upgrade-Contracts
    if: "startsWith(github.event.head_commit.message, '[upgrade-testnet]') && github.repository == 'subquery/network-contracts' || github.event_name == 'workflow_dispatch'"
    runs-on: ubuntu-latest
    env:
      SEED: ${{ secrets.SEED }}
    steps:
      #Check out
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'

      - run: yarn

      - name: Bump & Build
        run: npm version prerelease --no-git-tag-version && yarn build

      # Deploy contracts
      - name: Upgrade Changed Contracts
        run: yarn upgrade --${{ github.event.inputs.network }} && scripts/copy_deployment_json.sh # Uses SEED env var
        env:
          ENDPOINT: ${{ github.event.inputs.endpoint }}
          DEPLOY_PRINT: true

      - uses: JS-DevTools/npm-publish@v1
        name: Publish
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: dev
          access: public
          package: build/build/package.json

      # Commit updated contract addresses, this should trigger the prerelease action
      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        with:
          add: publish/*.json package.json
          message: '[SKIP CI] Deploy to testnet and Prerelease'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
